export const MessageTypes = {
	ANALYZE_REQUEST: 'TESTUDO_ANALYZE_REQUEST',
	ANALYZE_RESULT: 'TESTUDO_ANALYSIS_RESULT',
	CHECK_ADDRESS: 'TESTUDO_CHECK_ADDRESS',
	ADDRESS_CHECK_RESULT: 'TESTUDO_ADDRESS_CHECK_RESULT',
	RESOLVE_TOKEN: 'TESTUDO_RESOLVE_TOKEN',
	TOKEN_RESULT: 'TESTUDO_TOKEN_RESULT',
	GET_SETTINGS: 'TESTUDO_GET_SETTINGS',
	SETTINGS_RESULT: 'TESTUDO_SETTINGS_RESULT',
	RECORD_BLOCKED: 'TESTUDO_RECORD_BLOCKED',
} as const;

export type MessageType = (typeof MessageTypes)[keyof typeof MessageTypes];
