// Top 10K phishing domains as a base64-encoded bloom filter.
// Generated by scripts/build-phishing-seed.mjs (not yet implemented).
// For now, use an empty filter — CDN sync will replace this.
export const SEED_FILTER_B64 = '';
export const SEED_NUM_HASHES = 10;
