#!/bin/sh

echo "🔍 Running lint check..."
yarn lint || exit 1

echo "🏗️ Building packages..."
yarn build || exit 1

echo "🧪 Running unit tests..."
yarn workspace @testudo/core run test || exit 1
yarn workspace @testudo/extension run test || exit 1

echo "✅ All checks passed!"
